name: Lighthouse Audit Web Performance

on:
  repository_dispatch:
    types: [lighthouse-audit]
    inputs:
      app_name:
        description: 'Name of the application'
        required: true
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the application'
        required: true

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - name: URL Processing
        id: url_processor
        uses: ./.github/actions/url-processor
        with:
          app_name: ${{ github.event.inputs.app_name }}
          default_protocol: 'https://'

      - name: Set Environment Variables
        run: |
          echo "APP_NAME=${{ steps.url_processor.outputs.app_name_with_protocol }}" >> $GITHUB_ENV
          echo "APP_NAME_NO_PROTOCOL=${{ steps.url_processor.outputs.app_name_no_protocol }}" >> $GITHUB_ENV

      - uses: actions/checkout@v1
      - name: Generate Lighthouse Report
        uses: justinribeiro/lighthouse-action@master
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ env.APP_NAME }}
          wptConnectionSpeed: threegfast

      - name: debug result folder
        run: ls -la ./results

      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Rename lighthouse report folder
        run: mv ./results/* ./results/${{ ENV.APP_NAME_NO_PROTOCOL }}/${{ env.DATE }}

      - name: Saving Lighthouse Audit Artifacts
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-artifacts
          path: './results/${{ env.APP_NAME_NO_PROTOCOL }}/${{ env.DATE }}'

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO_URL }}
          ref: main
          token: ${{ secrets.CONFIG_PRIVATE_REPO_TOKEN }}
          path: private-repo

      - name: Commit decrypted file to private repo
        run: |
          mkdir -p "private-repo/${{ secrets.PERFORMANCE_FOLDER }}/lighthouse"
          cp -r ./results/${{ ENV.APP_NAME_NO_PROTOCOL }}/${{ env.DATE }}/* "private-repo/${{ secrets.PERFORMANCE_FOLDER }}/lighthouse"
          cd private-repo
          git add *
          git commit -m "Add lighthouse audit - ${{ env.APP_NAME_NO_PROTOCOL }} - ${{ env.DATE }}"
          git push origin main
