name: Lighthouse Audit Web Performance

on:
  repository_dispatch:
    types: [lighthouse-audit]
    inputs:
      app_name:
        description: 'Name of the application'
        required: true
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the application'
        required: true

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - name: Add protocol to app name if missing
        id: add-protocol
        run: |
          echo "app_name=${{ regex_replace(github.event.inputs.app_name, '^http', 'https') }}" >> $GITHUB_OUTPUT

      - name: Add app name with protocol to GITHUB_ENV
        run: echo "APP_NAME=${{ steps.add-protocol.outputs.app_name }}" >> $GITHUB_ENV

      - uses: actions/checkout@v1
      - name: Generate Lighthouse Report
        uses: justinribeiro/lighthouse-action@master
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ github.event.inputs.app_name }}
          wptConnectionSpeed: threegfast

      - name: debug result folder
        run: ls -la ./results

      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Rename lighthouse report folder
        run: mv ./results/* ./results/${{ github.event.inputs.app_name }}/${{ env.DATE }}

      - name: Saving Lighthouse Audit Artifacts
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-artifacts
          path: './results/${{ github.event.inputs.app_name }}/${{ env.DATE }}'

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO_URL }}
          ref: main
          token: ${{ secrets.CONFIG_PRIVATE_REPO_TOKEN }}
          path: private-repo

      - name: Commit decrypted file to private repo
        run: |
          mkdir -p "private-repo/${{ secrets.PERFORMANCE_FOLDER }}/lighthouse"
          cp -r ./results/${{ github.event.inputs.app_name }}/${{ env.DATE }}/* "private-repo/${{ secrets.PERFORMANCE_FOLDER }}/lighthouse"
          cd private-repo
          git add *
          git commit -m "Add lighthouse audit - ${{ github.event.inputs.app_name }} - ${{ env.DATE }}"
          git push origin main
