name: Sitespeed.io monitor
on:
  repository_dispatch:
    types: [sitespeed-audit]
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the application'
        required: true

jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: URL Processing
        id: url_processor
        uses: ./.github/actions/url-processor
        with:
          app_name: ${{ github.event.inputs.app_name }}
          default_protocol: 'https://'

      - name: Set Environment Variables
        run: |
          echo "APP_NAME=${{ steps.url_processor.outputs.app_name_with_protocol }}" >> $GITHUB_ENV
          echo "APP_NAME_NO_PROTOCOL=${{ steps.url_processor.outputs.app_name_no_protocol }}" >> $GITHUB_ENV

      - name: Get current timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      # - name: Rename sitespeed report folder
      #   run: |
      #     ls -la
      #     RESULTS_PATH="./sitespeed-result/${{ env.APP_NAME_NO_PROTOCOL }}/${{ env.TIMESTAMP }}"
      #     echo "RESULTS_PATH=$RESULTS_PATH" >> $GITHUB_ENV
      # globstar option allows the ** pattern to match directories recursively.

      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:34.3.1 "${{ env.APP_NAME }}" # --budget.configPath ../sitespeed.io/budget.json -n 1

      # - name: ls -la
      #   run: |
      #     ls -la
      #     cd results
      #     ls -la
      #     cd sitespeed-results || exit
      #     ls -la
      #     cd ${{ env.APP_NAME_NO_PROTOCOL }}
      #     ls -la

      # - name: Rename sitespeed report folder
      #   run: |
      #     shopt -s globstar
      #     ls -la
      #     mv ./sitespeed.io/sitespeed-results/${{ env.APP_NAME_NO_PROTOCOL }}/* "${{ env.RESULTS_PATH }}"
      #     shopt -u globstar

      - name: Upload sitespeed.io results
        uses: actions/upload-artifact@master
        with:
          name: sitespeed-results
          path: './sitespeed-result'

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.PRIVATE_REPO_URL }}
          ref: main
          token: ${{ secrets.CONFIG_PRIVATE_REPO_TOKEN }}
          path: private-repo

      - name: Commit files to private repo
        run: |
          # Define the destination path in the private repo
          PRIVATE_REPO_PATH="private-repo/${{ secrets.PERFORMANCE_FOLDER }}/sitespeed"

          # Create the destination directory
          mkdir -p "$PRIVATE_REPO_PATH"
          ls -la "$PRIVATE_REPO_PATH"
          # Copy the specific sitespeed result folder to the destination
          cp "*" "$PRIVATE_REPO_PATH"

          # Navigate to the private repository
          cd private-repo

          # Add, commit, and push the changes
          git add .
          git commit -m "Add sitespeed audit - ${{ env.APP_NAME_NO_PROTOCOL }} - ${{ env.TIMESTAMP }}"
          git push origin main
